[package]
name        = "pstore-index"
version     = "0.1.0"
edition.workspace     = true
rust-version.workspace = true
license.workspace     = true
repository.workspace  = true

[lints]
workspace = true

[dependencies]
bytes         = "1"
futures-util  = { version = "0.3", default-features = false, features = ["std", "alloc"] }
pstore-blob   = { path = "../pstore-blob" }
pstore-format = { path = "../pstore-format" }

[dev-dependencies]
bytes          = "1"
pstore-engine  = { path = "../pstore-engine" }
pstore-testkit = { path = "../pstore-testkit" }
pstore-types   = { path = "../pstore-types" }
tokio          = { version = "1", features = ["macros", "rt-multi-thread"] }
