#!/usr/bin/env python3
"""Every acceptance criterion has an evidence line, and every test it names is real.

OQ-167. Rung 3 of the gate-design ladder: a predicate over files in the tree, so no
agent is asked to check it.

⚠️ What it CANNOT see, stated because a documented blind spot beats an undocumented
mechanism that half works:
  * Whether the evidence is TRUE. It forces enumeration, which is what catches the
    quiet omission of criterion 6 -- not honesty, which no script can check.
  * Whether a named COMMAND actually demonstrates the criterion. A line naming
    `cargo test` and nothing else satisfies this gate and proves very little.
  * PARTIAL drift. If a line names three tests and one was renamed, the other two
    still resolve and the line passes. Detecting that would mean treating every
    backticked snake_case word as a test claim, which refuses the methods and
    probes evidence lines legitimately mention -- a false refusal gets a gate
    switched off, which enforces nothing at all. Caught only when a line's ONLY
    test claim has drifted.
  * Tests generated by a macro (proptest!, rstest parameterisation). The known-test
    set comes from a source scan, so a macro-generated name will not resolve. Name
    the enclosing #[test] fn, or mark the line NOT-RUN with a reason.
  * A milestone with no VERIFIED.md at all. That is in-progress work, not drift, and
    failing on it would be a false refusal that gets the gate switched off. The
    milestone skill demands the ledger at completion; this gate checks it once written.

  check-verified.py           check every docs/milestones/*/SPEC.md
  check-verified.py --self-test-fixture DIR   check one directory (used by the selftest)
"""
import re, sys, pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
# Uppercase and awkward to type by accident: writing one is a deliberate act.
HONEST_ABSTENTIONS = ("NOT-RUN", "OBSERVED-NOT")
# A backticked identifier that looks like a Rust test path.
IDENT = re.compile(r"`([A-Za-z_][A-Za-z0-9_]*(?:::[A-Za-z_][A-Za-z0-9_]*)*)`")
# Some criteria are demonstrated by a COMMAND rather than a test -- a coverage
# threshold, a gate sweep, an audit grep. That is legitimate evidence: it is
# reproducible by rerunning it. Found by the gate refusing its own project's
# criterion 8, which is the right kind of refusal to learn from.
COMMAND = re.compile(r"`((?:\./scripts/|cargo |grep )[^`]+)`")
TEST_ATTR = re.compile(r"#\[(?:tokio::|async_std::|rstest|test_case|proptest)?[a-z_:]*test[a-z_:(]*")


def known_tests() -> set[str]:
    """Every #[test]-adjacent fn name in the tree."""
    names: set[str] = set()
    for rs in ROOT.rglob("crates/**/*.rs"):
        lines = rs.read_text().splitlines()
        for i, line in enumerate(lines):
            if not TEST_ATTR.search(line):
                continue
            # The fn may be a few lines down past more attributes.
            for nxt in lines[i + 1 : i + 6]:
                m = re.search(r"\bfn\s+([A-Za-z_][A-Za-z0-9_]*)", nxt)
                if m:
                    names.add(m.group(1))
                    break
    return names


def ordered_items(text: str, section: str | None = None) -> dict[str, str]:
    """Top-level ordered list items -> their text. Liberal about the number, because
    a real ledger used `-1.` and `0.` for criteria that predated the numbering."""
    if section:
        m = re.search(rf"^##+\s*{re.escape(section)}\s*$(.*?)(?=^##\s|\Z)", text, re.M | re.S)
        if not m:
            return {}
        text = m.group(1)
    items: dict[str, str] = {}
    cur = None
    for line in text.splitlines():
        m = re.match(r"^(-?\d+)\.\s+(.*)$", line)
        if m:
            cur = m.group(1)
            items[cur] = m.group(2)
        elif cur and line.startswith(("   ", "\t")):
            items[cur] += " " + line.strip()
        elif line.strip() == "":
            continue
        else:
            cur = None
    return items


def check(milestone: pathlib.Path, tests: set[str]) -> list[str]:
    spec, verified = milestone / "SPEC.md", milestone / "VERIFIED.md"
    if not verified.exists():
        print(f"  skip {milestone.name}: no VERIFIED.md yet (in progress, not drift)")
        return []
    errs = []
    crit = ordered_items(spec.read_text(), "Acceptance criteria")
    if not crit:
        errs.append(f"{spec}: no numbered items under '## Acceptance criteria'")
        return errs
    ev = ordered_items(verified.read_text())

    for n in crit:
        if n not in ev:
            errs.append(f"{verified}: criterion {n} has no evidence line -- "
                        f"if it was not verified, say NOT-RUN and why")
    for n in ev:
        if n not in crit:
            errs.append(f"{verified}: evidence line {n} matches no criterion in SPEC.md")

    for n, line in ev.items():
        if n not in crit:
            continue
        if any(a in line for a in HONEST_ABSTENTIONS):
            continue
        # Strip command spans first, so `cargo test` inside a line naming a drifted test
        # cannot rescue it. The first version checked the command fallback before drift
        # and let exactly that through -- caught by the selftest.
        prose = COMMAND.sub("``", line)
        named = IDENT.findall(prose)
        resolved = [i for i in named if i.split("::")[-1] in tests]
        # ⚠️ Only when NOTHING on the line resolves. Evidence lines legitimately name
        # methods and probes in backticks (`should_rebase`, `aba_resistance`), and an
        # earlier version refused those -- a false refusal, which gate-design warns gets
        # a gate switched off rather than fixed. See the blind spot in the module docs.
        stale = (
            [i for i in named if "_" in i or "::" in i]
            if not resolved
            else []
        )
        if stale:
            # ⚠️ Checked BEFORE the command fallback. The first version let the fallback
            # run first, so a line naming a drifted test AND `cargo test` passed -- the
            # selftest caught it, which is why the fallback was added with a case.
            errs.append(f"{verified}: criterion {n} names {stale} which resolve to no "
                        f"test in the tree -- renamed, or the ledger drifted")
        elif not resolved and not COMMAND.search(line):
            errs.append(f"{verified}: criterion {n} names no resolvable test, no "
                        f"reproducible command, and is not marked "
                        f"{' or '.join(HONEST_ABSTENTIONS)}")
    return errs


def main() -> int:
    if "--self-test-fixture" in sys.argv:
        dirs = [pathlib.Path(sys.argv[sys.argv.index("--self-test-fixture") + 1])]
    else:
        dirs = sorted(p.parent for p in ROOT.glob("docs/milestones/*/SPEC.md"))
    tests = known_tests()
    if not dirs:
        # ⚠️ NOT the word "ok". A green line that means nothing is worse than a red one:
        # the source project had a gate print "ok nothing staged" and pass vacuously.
        print(f"nothing to check: no docs/milestones/*/SPEC.md exists yet "
              f"({len(tests)} tests known)")
        return 0
    errs: list[str] = []
    for d in dirs:
        errs += check(d, tests)
    if errs:
        print("FAIL VERIFIED.md ledger:", file=sys.stderr)
        print("\n".join(f"  {e}" for e in errs), file=sys.stderr)
        return 1
    print(f"ok {len(dirs)} milestone ledger(s), every criterion evidenced, "
          f"every named test resolves ({len(tests)} tests known)")
    return 0


sys.exit(main())
